export const EXPAND_MAINVIEW = 'EXPAND_MAINVIEW'
export const COLLAPSE_MAINVIEW = 'COLLAPSE_MAINVIEW'
export const EXPAND_REQUESTVIEW = 'EXPAND_REQUESTVIEW'
export const COLLAPSE_REQUESTVIEW = 'COLLAPSE_REQUESTVIEW'